### ISSUE TITLE
tns run android + Webpack AOT

### ISSUE THREAD

**Issue by dvdbrk** [sis0k0/lazyNinjas#10]
Any ideas how to have a child routes loaded in a way that works with both `tns run android` and `npm run start-android-bundle --aot`?

In my app I can load a lazy module from one sub directory level only, but any subsequent sub directories can not be found.

For example, in `app-routing` I have default route:

```
  {
    path: "",
    loadChildren: "./level1/level1.module#Level1Module"
  },
```

Then in `level1-routing`:

```
{
  path: "level-2",
  loadChildren: "./level2/level2.module#Level2Module"
},
```

So this reports an error when using `tns run android`: 
`JS: ERROR Error: Uncaught (in promise): Error: com.tns.NativeScriptException: Failed to find module: "/data/data/org.test.app/files/app/./level2/level2.module", relative to: app//`

When running `npm run start-android-bundle --aot` the above paths work well.

To fix this for the `tns run android` I need to use absolute paths - and then it works (but fails for webpack build). Any ideas?

**Comment by gtzinos** [comment]
Hi,
I have the same problem. I followed this guide (http://docs.nativescript.org/angular/best-practices/bundling-with-webpack.html#introducing-webpack) and i can't build your project cause i am getting this error 


ERROR in Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 'routes'. Consider exporting the symbol (position 5:7 in the original .ts file), resolving symbol routing in /my-path/lazyNinjas/app/app-routing.ts, resolving symbol AppModule in /my-path/lazyNinjas/app/app.module.ts, resolving symbol AppModule in /my-path/lazyNinjas/app/app.module.ts

Steps to reproduce:
1) Clone this project (Default branch)
2) npm install
3) npm install --save-dev nativescript-dev-webpack
4) npm install
5) npm run start-android-bundle

**Comment by sis0k0** [comment]
Hey guys, use the `aot` branch as it is now the recommended way. I made it a default. Please, reopen if you have any problems with it.
