### ISSUE TITLE
Can't run your project on ios

### ISSUE THREAD

**Issue by gtzinos** [sis0k0/lazyNinjas#12]
When i run `tns debug ios` it runs without error but when i execute `npm run start-ios-bundle` then it returns me this error message during compilation:

ERROR Error: A Frame must be used to navigate to a page.

*Info: I use your default branch

**Comment by sis0k0** [comment]
@gtzinos 

Updating the dependencies fixed that issue (see 29e82a34e7aa4ff81c2c563163bca313778183af). Sorry for the late answer :(. If you have any problems in terms of using lazy loading or webpack with NativeScript apps, don't hesitate to send me a mail (stanimira.vlaeva@gmail.com).
