### ISSUE TITLE
Can't run: @angular/core has no exported member StaticProvider

### ISSUE THREAD

**Issue by airandfingers** [sis0k0/lazyNinjas#14]
Hi, I'm trying to run the nested-lazy-modules branch to figure out why my own nested lazy modules aren't working (can't get the nested router to route).

I'm on NPM v5.3.0, tns v3.2.1.

After cloning, switching to nested-lazy-modules, and running "tns run [ios|android]", many packages install, and then I get these errors:

Android:

> + tns-android@3.0.0-rc.1
> added 1 package in 39.416s
> Project successfully created.
> Executing before-prepare hook from /Users/ayoshitake/lazyNinjas/hooks/before-prepare/nativescript-dev-typescript.js
> Found peer TypeScript 2.3.4
> node_modules/nativescript-angular/platform-common.d.ts(7,127): error TS2305: Module '"/Users/ayoshitake/lazyNinjas/node_modules/@angular/core/core"' has no exported member 'StaticProvider'.
> 
> node_modules/nativescript-angular/platform.d.ts(2,23): error TS2305: Module '"/Users/ayoshitake/lazyNinjas/node_modules/@angular/core/core"' has no exported member 'StaticProvider'.
> 
> Unable to apply changes on device: emulator-5554. Error is: TypeScript compiler failed with exit code 1.

iOS:

> + tns-ios@3.2.0
> added 117 packages in 29.285s
> Project successfully created.
> Executing before-prepare hook from /Users/ayoshitake/lazyNinjas/hooks/before-prepare/nativescript-dev-typescript.js
> Found peer TypeScript 2.3.4
> node_modules/nativescript-angular/platform-common.d.ts(7,127): error TS2305: Module '"/Users/ayoshitake/lazyNinjas/node_modules/@angular/core/core"' has no exported member 'StaticProvider'.
> 
> node_modules/nativescript-angular/platform.d.ts(2,23): error TS2305: Module '"/Users/ayoshitake/lazyNinjas/node_modules/@angular/core/core"' has no exported member 'StaticProvider'.
> 
> Unable to apply changes on device: BC6EBA8E-FBA9-4183-9E67-913BE8F17D25. Error is: TypeScript compiler failed with exit code 1.

Based on [this SO answer](https://stackoverflow.com/questions/36556709/angular-2-module-has-no-exported-member/41162492#41162492), it looks like this could be caused by a mismatch in the Angular package versions. I tried changing "~4.2.0" in package.json to "latest", but I still get this error.

**Comment by rAnAaRsl** [comment]
1+

**Comment by Dimitrievskislavcho** [comment]
+1

**Comment by ESemion17** [comment]
+1

**Comment by MuhammadTahir92** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by sis0k0** [comment]
Heya, I've updated the `aot` branch to the latest versions of NativeScript and Angular. I'll updated the other branches later :)

**Comment by sis0k0** [comment]
Hey everyone! I've updated the app to the latest {N} and Angular versions and it works again :). Feel free to comment here if you're experiencing the same problem.

**Comment by OlatunjiGab** [comment]
Typescript Error
Module '"C:/Users/Gabriel/Documents/GabFile/MyProject/FPImobile/node_modules/@angular/core/core"' has no exported member 'StaticProvider'.
...t/FPImobile/node_modules/@angular/forms/src/directives/range_value_accessor.d.ts
*
*  ### Example
*  ```
Typescript Error
Module '"C:/Users/Gabriel/Documents/GabFile/MyProject/FPImobile/node_modules/@angular/core/core"' has no exported member 'StaticProvider'.
...le/node_modules/@angular/forms/src/directives/select_control_value_accessor.d.ts
* Used by {@link NgModel}, {@link FormControlDirective}, and {@link FormControlName}
* to keep the view synced with the {@link FormControl} model.
*
Typescript Error
Module '"C:/Users/Gabriel/Documents/GabFile/MyProject/FPImobile/node_modules/@angular/core/core"' has no exported member 'StaticProvider'.
...odules/@angular/forms/src/directives/select_multiple_control_value_accessor.d.ts
*  ### Caveat: Options selection
*
* Angular uses object identity to select options. It's possible for the identities of items
Typescript Error
Module '"C:/Users/Gabriel/Documents/GabFile/MyProject/FPImobile/node_modules/@angular/core/core"' has no exported member 'StaticProvider'.
...e/MyProject/FPImobile/node_modules/@angular/forms/src/directives/validators.d.ts
};
/**
 * An interface that can be implemented by classes that can act as validators.
Typescript Error
Argument of type '{ declarations: (typeof AboutPage | typeof MapPage | typeof TimetablePage | typeof SchoolPage | t...' is not assignable to parameter of type 'NgModule'. Types of property 'providers' are incompatible. Type '(typeof SplashScreen | typeof NativeGeocoder | typeof YtProvider | typeof AngularFireAuth | typeo...' is not assignable to type 'Provider[]'. Type 'typeof SplashScreen | typeof NativeGeocoder | typeof YtProvider | typeof AngularFireAuth | typeof...' is not assignable to type 'Provider'. Type 'FilePathOriginal' is not assignable to type 'Provider'. Type 'FilePathOriginal' is not assignable to type 'FactoryProvider'. Property 'provide' is missing in type 'FilePathOriginal'.
C:/Users/Gabriel/Documents/GabFile/MyProject/FPImobile/src/app/app.module.ts
@NgModule({
  declarations: [

Any help pls

**Comment by OlatunjiGab** [comment]
This is my ionic info
Ionic:

   ionic (Ionic CLI)  : 4.12.0
   Ionic Framework    : ionic-angular 3.9.8
   @ionic/app-scripts : 3.2.4

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : android 6.1.2
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 16 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\Gabriel\AppData\Local\Android\Sdk)
   NodeJS            : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.10.3
   OS                : Windows 10
