### ISSUE TITLE
Putting *ngIf in template causes "Property binding" error.

### ISSUE THREAD

**Issue by dxshindeo** [sis0k0/lazyNinjas#4]
Trying out the  `callback-loading` way. Seems to work fine, but if I put any `*ngIf` in template, it throws me an error: 

> Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations".

**Comment by sis0k0** [comment]
Hey @dxshindeo,
You should import the `CommonModule` either in the root module (`AppModule`), or in the module that you want to use *ngIf in (e.g. `NinjasModule`).

``` ts
import { CommonModule } from "@angular/common";
...
@NgModule({
    imports: [CommonModule]
    ...
})
export class AppModule { }
```

**Comment by dxshindeo** [comment]
Thanks for super-fast reply. Defining it in root module doesn't do, however defining it on specific modules does. Big thanks!

**Comment by ronny98** [comment]
still not works kindly figure it

**Comment by egodefroy** [comment]
@dxshindeo:; it can work if you add it to an 'exports' section too
