### ISSUE TITLE
ListView doesn't act as it is supposed to in lazy loaded component

### ISSUE THREAD

**Issue by dxshindeo** [sis0k0/lazyNinjas#5]
I have an array of data which I want to list. 

```
<ListView [items]="globalsService.results">
	<template let-item="item">
		<Label text="{{ item.main_text }}"></Label>
	</template>
</ListView>
```

It was working correctly, but after I lazy loaded this component it simply gives `[object Object]` instead of list items. How to fix this?

**Comment by dxshindeo** [comment]
Well, after much trial and error I managed to make it work by converting code to ScrollView:

```
<ScrollView>
	<StackLayout>
		<StackLayout *ngFor="let item of globalsService.results">
			<Label text="{{ item.main_text }}"></Label>
		</StackLayout>
	</StackLayout>
</ScrollView>
```

Still curious why ListView broke...

**Comment by dlucidone** [comment]
@sis0k0 hey, any solutions on this, as i have majorily worked on listview. and the above solution is throwing -

`JS: Property binding ngForOf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations".`

Error like this. Help .Thanks

**Comment by dxshindeo** [comment]
Oh I can help you with that error - lets say your component is called `my_comp.component.ts`. Now, in your `my_comp.module.ts` make sure you add CommonModule like this:
```
import { CommonModule } from "@angular/common";

@NgModule({
    imports: [
    	CommonModule,
        ...
    ],
...
```
Adding it globally in `app.module.ts` would work only if you don't use lazy loading.

**Comment by sis0k0** [comment]
Hey @dxshindeo.,
Sorry for the late reply. If you need to use `template` in your components, you have to import`NativeScriptModule`. For example, if you are using `ListView` with `template` in your `HomeComponent`, you have to import `NativeScriptModule` in `HomeModule`.

``` ts
import { NativeScriptModule } from "nativescript-angular/nativescript.module";
...
@NgModule({
    imports: [
        NativeScriptModule,
        ...
    ],
    ...
})
```

I wanted this app to be as simple as possible, but it's probably a good idea to have `NativeScriptModule` imported in all `NgModules`. Thanks for the feedback!

**Comment by dxshindeo** [comment]
Oh, I had it there already.
So, `*ngIf` and other angular directives come from `CommonModule`, but the ones like `ListView` comes from `NativescriptModule`. Makes sense, thanks for clarifying!

**Comment by sis0k0** [comment]
Yep, that's right. You may also check [this article](https://medium.com/@alexander.vakrilov/faster-nativescript-listview-with-multiple-item-templates-8f903a32e48f#.785zfnyms) on the benefits of using `template` instead of `ngFor`.
