### ISSUE TITLE
IOS Error - EXCEPTION: Uncaught (in promise): Error: No provider for ViewUtils!

### ISSUE THREAD

**Issue by tskweres** [sis0k0/lazyNinjas#6]
I follow the simple installation instructions:

$ git clone https://github.com/sis0k0/lazyNinjas.git
$ cd lazyNinjas
$ tns livesync ios --watch

And I receive this error:

EXCEPTION: Uncaught (in promise): Error: No provider for ViewUtils!

**Comment by tskweres** [comment]
Update package.json to all of the latest and you're good to go

**Comment by sis0k0** [comment]
Thanks! I updated the repo to use next version of nativescript-angular.
