### ISSUE TITLE
Why are you Importing the HomeModule in AppModule ?

### ISSUE THREAD

**Issue by hiddencaliber** [sis0k0/lazyNinjas#8]
I am trying to similar to the link below -

https://github.com/NativeScript/nativescript-dev-webpack/issues/81

Please help.

Thanks,

**Comment by sis0k0** [comment]
Because the app should know about it somehow.
https://angular.io/docs/ts/latest/guide/ngmodule.html#!#feature-modules

**Comment by hiddencaliber** [comment]
Hi,

Thanks for responding, I am trying to fix some lazy loaded module issue and got confused.
Obviously, HomeModule is not lazy loaded here. Sorry to bug you with silly question.

Thanks a lot.
